### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by JamieSlome** [LukGit/local-news-weather-frontend#1]
Hello @LukGit,

We recently received a disclosure against your repository from @gewoonjaap. I was not able to find a contactable e-mail address or defined security process to follow to notify you of this.

If you would like to details of this, feel free to provide an e-mail or another way I can get in touch to share this with you, and I will be happy to facilitate this.

Otherwise, you can visit the advisory page [here](https://huntr.dev/bounties/1-other-LukGit/local-news-weather-frontend/). This is private and only accessible to yourself and the discloser.

If you have any questions, let me know!

-- Jamie from huntr.dev 🍰

**Comment by LukGit** [comment]
This is only a class project and never intended to be publish in any shape or form. You want me to take it off github?

**Comment by JamieSlome** [comment]
Not at all! No action is required here, thanks for the information!

Closing the issue...
